# Generated by Django 3.0.3 on 2020-02-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('desc', models.TextField()),
                ('school', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics/')),
            ],
        ),
    ]
